### ISSUE TITLE
Using w/Handlebars

### ISSUE THREAD

**Issue by davidkaneda** [emmetio/emmet#109]
I'm having trouble getting the tab completion to work with Handlebars in ST2. I've tried adding text.html.handlebars to the tab completion scope setting in .sublime-keymap, as well as adding "hbs/handlebars": {extends: "html"} in user prefs, but no luck. Has anyone else tried this? Thanks-

**Comment by calicraftcocktails** [comment]
Old issue but for others since I've been trying to fix this for a few hours - `text.html.handlebars` doesn't seem to work using the Ember Syntax highlighter, since `.hbs` files are defined as Glimmer files.

Copying over the two `tab` handlers from default key bindings and adding `source.handlebars` to the operands for each fixed it for me.
