### ISSUE TITLE
auto convert html tags to scss (like emmet, but backwords)

### ISSUE THREAD

**Issue by elron** [emmetio/emmet#356]
Hi guys,
If you're using sass/less/scss this might interest you.

will you take a moment to check my question?
http://stackoverflow.com/questions/27723676/convert-html-tags-to-scss-less

Thanks :smiley:
Elron

https://github.com/eddiemachado/bones/issues/722#issuecomment-68455392
##

**Comment by sergeche** [comment]
This is pretty useless feature. Mostly because generic solution will generate very verbose output. E.g. should it include tag names, ID and/or class (if both in one element), include all intermediate/parent selectors or just some of them etc. In other words, you’ll find yourself wasting time on shaping up output.

You shouldn’t think about your workflow improvement like “less typing == more productivity”. You should think about how much time you spend on completing your task. And using tools that create obstacles in first place rather than solving your problem won’t improve your workflow.
