### ISSUE TITLE
Allow special characters as part of class name

### ISSUE THREAD

**Issue by paulozoom** [emmetio/emmet#443]
This abbreviation:

```html
.box.width-1/2
```

expands to

```html
.box.width-1/<2></2>
```

However, a slash is perfectly valid in the HMTL class attribute, since CSS lets one escape characters. Is there a way to allow for this, or configure Emmet to change which characters constitute delimiters of abbreviations?

**Comment by sergeche** [comment]
`/` is not a valid character for Emmet and I think it won’t be added in future (at least in this context). As a workaround: `.box[class='width-1/2']`

**Comment by paulozoom** [comment]
@sergeche thanks for chiming in. Any thoughts on letting users configure delimiting characters?

**Comment by sergeche** [comment]
No, it’s actually not that trivial: there’s a mechanism for properly extracting abbreviations from source code. For example, in `<div>foo>bar` Emmet extracts `foo>bar`, not `div>foo>bar` because it’s able to detect HTML tags. Adding custom characters into abbreviation may introduce invalid abbreviations in some cases.

**Comment by paulozoom** [comment]
@sergeche Got it.
