### ISSUE TITLE
Insertion of new lines in output

### ISSUE THREAD

**Issue by pitommasi** [emmetio/emmet#642]
Hi, 

I'm in VS Code, I'd like to add a new line and a tab in a snippet but it's broken.

Here's the syntax I've tried:

`figure{\n\t}>img`

I expected to have

```html
<figure>
    <img src="" alt="">
</figure>
```

but instead got:

`<figure> <img src="" alt=""></figure>`

**Comment by pitommasi** [comment]
Any update about this?

**Comment by sergeche** [comment]
While I’ve fixed issue with preserving whitespace characters in text nodes, it won’t work as you expect in this case due to very complex output indentation precess. If you output as above, there are plenty of options that you can tune to get the desired output:

* [output.inlineBreak](https://github.com/emmetio/emmet/blob/master/src/config.ts#L129)
* [output.formatForce](https://github.com/emmetio/emmet/blob/master/src/config.ts#L122)
* ['output.formatLeafNode](https://github.com/emmetio/emmet/blob/master/src/config.ts#L116)
