### ISSUE TITLE
Tailwind Support

### ISSUE THREAD

**Issue by sprankhub** [emmetio/emmet#668]
I am not sure if this is something, which fits well into Emmet, but I think it does. Did you ever consider Emmet support for Tailwind classes? Many Tailwind classes are short by default, but there are still possible abbreviations, which would be helpful. Examples:

* `tb` => `text-base`
* `fb` => `font-bold`
* `tc500` => `text-cyan-500`
* `ic` => `items-center`

Thoughts?

Thanks!

**Comment by sergeche** [comment]
The best solution here is to use native host editor snippets, this is exactly how they should be used

**Comment by sprankhub** [comment]
Thanks for the quick answer, @sergeche :)

Are you referring to https://docs.emmet.io/customization/snippets/? So you do not think this would be a good addition to the core? Since Tailwind is not project-specific, I am not sure if `snippets.json` is a good solution to this.

**Comment by sergeche** [comment]
No, I’m referring to native snippets in editor you’re using. Something like this: https://docs.sublimetext.io/guide/extensibility/snippets.html#snippets-file-format

**Comment by sprankhub** [comment]
Okay, can you elaborate why you think this is not a good addition to Emmet itself?

**Comment by sergeche** [comment]
Emmet produces structured output dynamically: it takes basically any word and produces tags from it. That’s why it limits itself to specific code places where it can be activated: you wouldn’t expect HTML  tags white typing HTML attribute name or attribute value, right?

What I see from Tailwind docs is that it’s just a bunch of predefined utility classes. There’s nothing dynamic about it and they are tied specifically to `class="..."` attribute value (where Emmet shouldn’t work by design since it’s used to produce HTML markup). 

Your case is exactly what editors’ text snippets should be used for: in editors like Sublime Text or VSCode you can create a list of static snippets what should work inside `class="..."` and provide nice completions popup
